# Change these first
owner: zzc-tongji # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: S3 File Management
    url: https://f.$DOMAIN_US/
  - name: S3 File Service
    url: https://file.$DOMAIN_US/
  - name: GitHub Proxy Service
    url: https://gh.$DOMAIN_US/https://api.github.com/
#
  - name: OSS File Service
    url: https://file.$DOMAIN_CN/
  - name: Feishu Service
    url: https://feishu.$DOMAIN_CN/
#
  - name: FRP Service
    url: origin.$DOMAIN_CN
    port: 60000
    check: "tcp-ping"
  - name: MIX2 at FRP
    url: origin.$DOMAIN_CN
    port: 60001
    check: "tcp-ping"
  - name: N40 at FRP
    url: origin.$DOMAIN_CN
    port: 60002
    check: "tcp-ping"
  - name: UM300 at FRP
    url: origin.$DOMAIN_CN
    port: 60003
    check: "tcp-ping"
#
  # - name: MIX2 at Home
  #   url: home.$DOMAIN_CN
  #   port: 60001
  #   check: "tcp-ping"
  - name: N40 at Home
    url: home.$DOMAIN_CN
    port: 60002
    check: "tcp-ping"
  - name: UM300 at Home
    url: home.$DOMAIN_CN
    port: 60003
    check: "tcp-ping"
#
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://upptime.js.org/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  apiBaseUrl: https://api.github.com/
  userContentBaseUrl: https://raw.githubusercontent.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
